### ISSUE TITLE
styleA.css format looks off

### ISSUE THREAD

**Issue by DiegoLopezInc** [1213-Throwback/ITSC-3155-002-PROJECT-ONE#1]
**This:**
![image](https://github.com/1213-Throwback/ITSC-3155-002-PROJECT-ONE/assets/123400127/49cf71c0-51da-46ae-b4ef-731e9994080c)

**This doesn't match this:**
![image](https://github.com/1213-Throwback/ITSC-3155-002-PROJECT-ONE/assets/123400127/fa74a731-38ad-4530-9e33-68ffa31b191f)

**Please fix** 👍

**Comment by ghost** [comment]
Here is the updated version. I fixed the code by changing the background colors, fonts, and sizes of all of the boxes. I also went ahead and centered the boxes. 
![image](https://github.com/1213-Throwback/ITSC-3155-002-PROJECT-ONE/assets/112581503/2953fbe9-b37a-4161-93f7-555db2f56f08)
This should be a finished product for Style A
