### ISSUE TITLE
User Story Template Development

### ISSUE THREAD

**Issue by DiegoLopezInc** [1213-Throwback/ITSC-3155-002-PROJECT-ONE#2]
**User Story Template:**
“As a [persona], I [want to], [so that].”

**Our User Story:**
“As a student, I want to complete project 1, so we get an A.”

What do y'all think? :D

**Comment by Vulcran** [comment]
**_As a_** business owner, **_I want_** one line of code on my website to change its entire appearance, **_so that_** I can switch between my holiday style website and my normal website without needing coding experience.

**Comment by Vulcran** [comment]
Issue Closed
