### ISSUE TITLE
styleC.css Extra Credit Design

### ISSUE THREAD

**Issue by DiegoLopezInc** [1213-Throwback/ITSC-3155-002-PROJECT-ONE#4]
What do we want the extra credit file to look like? **How about this???**

https://github.com/1213-Throwback/ITSC-3155-002-PROJECT-ONE/assets/123400127/6f647a6e-007c-4074-98db-8af1c2b184b0

**Thoughts?**

**Comment by albert-bastakoti** [comment]
I made the button change through the colors of the rainbow when clicked.

https://github.com/1213-Throwback/ITSC-3155-002-PROJECT-ONE/assets/143361459/36e67751-9c12-47fc-a68f-f44a71be1f39
